version: '2'
services:
  unado-api:
    container_name: unado-api
    image: dieosiris23/unado-api
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTHENTICATION_PORT: '4000'
      AUTHENTICATION_ENTRY: 'users'
      AUTH_PORT: '4000'
      AUTH_ENTRY: 'ldap/'
      USERS_PORT: '3000'
      USERS_ENTRY: '/'
      BOARDS_URL:  'boards-ms'
      BOARDS_PORT: '3001'
      BOARDS_ENTRY: 'boards-ms/resources/boards'
      LISTS_URL:  'lists-ms'
      LISTS_PORT: '3002'
      LISTS_ENTRY: 'lists-ms/resources/lists'
      TASKS_URL:  'tasks-ms'
      TASKS_PORT: '3003'
      TASKS_ENTRY: 'tasks-ms/resources/tasks'
      STATISTICS_URL: 'statistics-ms'
      STATISTICS_PORT: '3007'
      STATISTICS_ENTRY: 'statistics-ms/resources/statistics'
  #Examples MS
  examples-db:
    image: mysql:5.7
    ports:
      - "3309:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: examples
      MYSQL_HOST: examples-db
  examples-ms:
    image: dafrodriguezro/2b_example
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 4001 -b '0.0.0.0'"
    environment:
      PORT: '4001'
    depends_on:
      - examples-db
  lists-db:
    container_name: lists-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lists
      MYSQL_USER: listsuser
      MYSQL_PASSWORD: listsuser
    ports:
      - 3305:3306
  lists-ms:
    container_name: list-ms
    image:  dieosiris23/task3
    depends_on:
      - lists-db
  boards-db:
    container_name: boards-db
    image: mongo
    ports:
      - 3304:27017
  boards-ms:
    container_name: boards-ms
    image: baangaritar/boards-js
    depends_on:
      - boards-db
  tasks-db:
    container_name: tasks-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: tasks-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa
    ports:
      - 3306:3306
  tasks-ms:
    container_name: tasks-ms
    image: dieosiris23/task_ms
    environment:
      PORT: '3003'
    depends_on:
      - tasks-db
    #Authentication MS
  users-db:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: arquisoft
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: auth
      MYSQL_HOST: users-db
  users-ms:
    image: baangaritar/2e_unaldo_users
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails db:seed && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - 4000:4000
    depends_on:
      - 'users-db'
  statistics-ms:
    container_name: statistics-ms
    image: dieosiris23/statistics-py
    command: ["gunicorn", "statistics_ms.wsgi:application", "--bind", "0.0.0.0:8000"]
    environment:
      - SECRET_KEY=statistics
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=statistics-db
      - SQL_PORT=5432
    depends_on:
      - statistics-db
  statistics-db:
    container_name: statistics-db
    image: postgres
  #LDAP
  ibis-ldap:
    image: osixia/openldap:1.1.8
    container_name: ibis-ldap
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Ibis Dicsite"
      LDAP_DOMAIN: "arqsoft.unal.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "arqsoft.org"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ibis-ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    links:
      - ibis-ldap
  trello-proxy:
    container_name: trello-proxy
    image: dieosiris23/trello_proxy
    ports:
      - "80:80"
