version: '2'
services:
  unado-api:
    container_name: unado-api
    image: dieosiris23/unado-api
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      USERS_PORT: '3000'
      USERS_ENTRY: '/'
      BOARDS_URL:  'boards-ms'
      BOARDS_PORT: '3001'
      BOARDS_ENTRY: 'boards-ms/resources/boards'
      LISTS_URL:  'lists-ms'
      LISTS_PORT: '3002'
      LISTS_ENTRY: 'lists-ms/resources/lists'
      TASKS_URL:  'tasks-ms'
      TASKS_PORT: '3003'
      TASKS_ENTRY: 'tasks-ms/resources/tasks'
      STATISTICS_URL: 'statistics-ms'
      STATISTICS_PORT: '3007'
      STATISTICS_ENTRY: 'statistics-ms/resources/statistics'
  lists-db:
    container_name: lists-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lists
      MYSQL_USER: listsuser
      MYSQL_PASSWORD: listsuser
    ports:
      - 3305:3306
  lists-ms:
    container_name: list-ms
    image:  dieosiris23/task3
    depends_on:
    - lists-db
  boards-db:
    container_name: boards-db
    image: mongo
    ports:
      - 3304:27017
  boards-ms:
    container_name: boards-ms
    image: baangaritar/boards-js
    depends_on:
      - boards-db
  tasks-db:
    container_name: tasks-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: tasks-db
      MYSQL_PASSWORD: '123'
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_USER: sa
    ports:
      - 3306:3306
  tasks-ms:
    container_name: tasks-ms
    image: dieosiris23/task_ms
    environment:
      PORT: '3003'
    depends_on:
      - tasks-db
  statistics-ms:
    container_name: statistics-ms
    image: dieosiris23/statistics-py
    command: ["gunicorn", "statistics_ms.wsgi:application", "--bind", "0.0.0.0:8000"]
    environment:
      - SECRET_KEY=statistics
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=statistics-db
      - SQL_PORT=5432
    depends_on:
      - statistics-db
  statistics-db:
    container_name: statistics-db
    image: postgres
  trello-proxy:
    image: dieosiris23/trello_proxy
    depends_on:
       container_name: trello-proxy
       image: dieosiris23/trello-proxy
       ports:
         -"80:80"
